### ISSUE TITLE
Too many open files installing on mac OS.

### ISSUE THREAD

**Issue by philderbeast** [quickstrom/quickstrom#109]
**Describe the bug**
Following the [nix install instructions](https://docs.quickstrom.io/en/latest/installation/nix.html) fails with "too many open files" on mac OS.

**To reproduce**
```
> nix-env -iA quickstrom -f https://github.com/quickstrom/quickstrom/tarball/main
error: opening directory
'/nix/store/h3kl0ai30kd83s0ygq0spkqj19p1fgm0-https___registry.npmjs.org_braces___braces_3.0.2.tgz':
Too many open files
```

**Expected behaviour**
Could we add a note to the docs on how to work around this limit?

**Environment (please complete the following information):**
```
> cachix --version
cachix 0.6.1
> nix --version
nix (Nix) 2.4
> sw_vers
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224
```

**Additional context**
How do I [set the ulimit](https://stackoverflow.com/questions/49301678/how-do-i-set-the-ulimit-in-a-nix-build-shell)  in a nix build shell?

**Comment by owickstrom** [comment]
Wow, all right. Thanks for finding a workaround. I can add a note in the docs.
