### ISSUE TITLE
Upload artifact with documentation in GitHub Action

### ISSUE THREAD

**Issue by owickstrom** [quickstrom/quickstrom#19]

**Comment by Cmdv** [comment]
so I've been reading some docs!! felt it was wise after my last mistake!! lol

looking at the actions you currently have in `test.yaml` the chachix part is right and every time `cachix/cachix-action@v6` that would build it then upload it.

so I think I've worked out the uploading artifacts there is this https://github.com/marketplace/actions/upload-a-build-artifact
I'm not entirely sure what artifacts you'd want uploading though.

and for the documentation I spotted the project uses Sphinx so this action should do the trick for building the docs and uploading them to `gh-pages`:
https://github.com/marketplace/actions/sphinx-build

here is the part where it talks about putting things to gh-pages, would need to work out exactly how to put it into a specific folder (getting late too many docs for one day for me hehe)
https://github.com/ammaraskar/sphinx-action/blob/d13c86e3e3e6ccee46cdf8023e977694a8692e70/README.md#great-actions-to-pair-with

So all I need is what artifacts do you want uploading?

**Comment by owickstrom** [comment]
OK, so this about uploading the built documentation for a PR as an artifact of that PR. The reason is I want us to be able to review people's changes in documentation in rendered form.

Nix already builds the docs, so we don't need to mess around with Sphinx builders or such. The command you want is something like:

```
cp -r --no-preserve=mode,timestamps,ownership $(nix-build docs -A site --no-out-link) /tmp/docs
```

And then configure the artifact uploading action to make an artifact out of `/tmp/docs`. I think you might need this preview version v2 to upload an entire directory, not sure: https://github.com/actions/upload-artifact/tree/v2-preview#upload-artifact-v2

**Comment by owickstrom** [comment]
Fixed by the new Read the Docs setup.
