### ISSUE TITLE
within/outside action selector combinators

### ISSUE THREAD

**Issue by owickstrom** [quickstrom/quickstrom#20]
As per https://twitter.com/janiczek/status/1297682247013879808.

**Comment by jleonard-r7** [comment]
FYI... as of action seqs / await, it is possible to make sections of actions "off limits" with the following codes:

```
  Tuple prob $ Sequence [(AwaitWithTimeoutSecs 1 "#some-prereq"), otherActions...]
```

Note that this does introduce a delay of 1 second if this action is selected and the some-prereq isn't present but that seems like a very reasonable tradeoff for real world scenarios. (That also can be reduced once we refactor `awaitElement` to allow arbitrary delays).

**Comment by owickstrom** [comment]
I've not seen enough need for this feature, so I'm closing it for now. We can revisit if there are users that want it later on.
