### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by owickstrom** [quickstrom/quickstrom#21]
Many webapps authenticate users. Quickstrom needs to handle this, perhaps in one (or several) of the following ways:

1. Require webapps to provide special support, e.g.:
     - a non-authenticated mode, for instance in their test environments
     - URL-based overrides, like https://twitter.com/janiczek/status/1297667321574625281
1. Make it possible to configure the runner to "be authenticated", e.g.:
    - a parameter for setting cookies
    - a parameter for specifying basic authentication credentials
1. Add support for "action sequences", i.e. fixed sequences of actions that are always taken in their entirety, which could used to fill login forms, navigate OAuth flows, etc

**Comment by jleonard-r7** [comment]
It is arguable that this is now supported as of #61 and #63 being completed. Certainly it is working for our "login" use case (which I imagine is about as complicated as anyone's would be).

e.g., this is the relevant spec snippet:

```
readyWhen :: Selector
readyWhen = "input#signin-username"

usernameEntry :: Array BaseAction
usernameEntry = [
  (Focus "#signin-username")
  , (EnterText "username@somewhere.org")
 ]

passwordEntry :: Array BaseAction
passwordEntry = [
  (Focus "input#signin-password")
  , (EnterText "password")
]

loginSubmit :: Array BaseAction
loginSubmit = [
  (Click "input#signin-submit")
  , (Await "h2.page-title") -- some element on your "main landing page"
  , (Navigate "https://inner_url") -- the subsection you wish to test
  , (Await "#main-app") -- would be the `readyWhen` in a non-auth scenario
]

loginSeq1 :: Action
loginSeq1 = Sequence (usernameEntry <> passwordEntry <> loginSubmit)

loginSeq2 :: Action
loginSeq2 = Sequence (passwordEntry <> usernameEntry <> loginSubmit)

actions :: Actions
actions = [
  Tuple 10 loginSeq1
  , Tuple 10 loginSeq2
] <> clicks <> foci
```

**Comment by owickstrom** [comment]
Yeah, let's open up new (more specific) issues if other login methods are needed.
