### ISSUE TITLE
Set check options in specification code

### ISSUE THREAD

**Issue by Cmdv** [quickstrom/quickstrom#23]
I'm just going through the project with a fresh pair of eyes, thinking about how a new user would interact with Quickstrom. Here's what I'm wondering:

When looking at the examples the tests are ran using the cli, but I wonder if some of the attributes passed to the cli can in fact be in the tests/specs? eg: 
https://github.com/quickstrom/quickstrom/blob/9e74c0da944799ae9d3520dc67c576c1fbd8c7e8/specs/run-all.sh#L49
can `http://todomvc.com/examples/vue/` be set as part of a top level spec file, or some sort of a runner from within the specs?

When looking at projects like Puppeteer, you can have full control of the test runner from within the specs. (ignoring it's JS!)

```JS
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.goto('https://www.google.com/') // this line telling test runner where to go
  page.on('dialog', async dialog => {
    console.log(dialog.message())
    await dialog.dismiss()
  })
  await page.evaluate(() => alert('This message is inside an alert box'))
  await browser.close()
})()
```

Even if it's not inline as part of a spec file, but could be a top level runner:
```Purescript
module Runner where

import Quickstrom (Options(..), Flags(..), Results(..), runQuickStromIO)
import Spec1 (spec1)
import Spec2 (spec2)


main = do
  runQuickStromIO [ { spec: spec1
                    , loc: "../MultiPage.html"
                    , opts: [Options]
                    , flags: [Flags]
                    , res: Result
                  ]
  runQuickStromIO [ { spec: spec2
                    , loc: "http://www.webA.com"
                    , opts:[Options]
                    , flags: [Flags]
                    , res: Result 
                    }
                  , { spec: spec2
                    , loc:  "http://www.webB.com" 
                    , opts: [Options] 
                    , flags: [Flags]
                    , res: Result
                    }
                  ]
```

Ignoring my terrible naming conventions and if you'd even use records, but the idea being you have control of what the test runner is doing from within the code you are writing the specs/test.

Under the hood it would probably just be using the cli directly and from there could control styling of outputs etc.

This would help with context switching, because how likes to write shell scripts hehe

**Comment by Cmdv** [comment]
ps: totally non related but I have to vent my pain somewhere, nix is great but not on osx 😢
I'm still building from original `nix-shell` that's 5 hours!!! 😂

**Comment by amitu** [comment]
@Cmdv it took me that much or more to build. Good news it does end up compiling after all that. Have you tried using cachix? Supposedly it will make it faster, but I haven't gotten around to testing it yet.

**Comment by Cmdv** [comment]
@amitu yeah it built in the end (6 hours lol) and I do have cachix but didn't realise you could use it to build the full project!! was it just `chachix use quickstrom`?

Maybe I should add how to install things as contributors 🤔

**Comment by Cmdv** [comment]
@amitu yes it's my bad I should have read the provided instructions!! I don't need a manual!!! will the 6 hours wait make me learn? I doubt it very much!! lol

**Comment by owickstrom** [comment]
> @amitu yeah it built in the end (6 hours lol) and I do have cachix but didn't realise you could use it to build the full project!! was it just `chachix use quickstrom`?
> 
> Maybe I should add how to install things as contributors thinking

I've added a link from the README to CONTRIBUTING.md. Maybe there should be one in the user guide, too? But I'm hesitant, I think the user guide should only be directed at "end users". If there are weird things that require people to clone the repo, then we should fix those problems instead.

**Comment by owickstrom** [comment]
Regarding your question @Cmdv , this is something that I've actually changed _away from_. The _origin URL_, e.g. `http://todomvc.com/examples/vue/`, was previously specified as a top-level definition `origin` in the spec module.

I needed a single specification to be usable with many different origin URLs (all the TodoMVC implementations!). And I imagined people reusing their specs to run them locally, in dev environments, and maybe in prod, for instance.

But if we changed it so that the _check options_ (those that are currently given as CLI parameters) could be optionally set directly in the spec, it would be fine. We could have a resolution mechanism where the first available value for a check option is chosen, in the order:

1. specified as a top-level definition in the spec module
2. set as a CLI parameter
3. (environment variable?)
4. default value, if available

And if no value is available, Quickstrom would fail with an error.

**Comment by Cmdv** [comment]
Ah yes that makes sense, I might have a little dig around see if I can implement an origin URL through all 4 steps. Then if that works it shouldn't be too complex to add any other attributes.

One thing is how do you envision "a top-level definition in the spec module" looking like?

Without having looked too deeply into the inner workings, am I right in saying things are currently set up to work on a per spec basis?

**Comment by owickstrom** [comment]
Cool! I'm thinking the `CheckOptions` could be parameterized with a function, making it an `HFunctor`:

```haskell
data CheckOptions f = CheckOptions { checkTests :: f Int, checkOrigin :: f Text, ... } -- and so on
```

And the different sources of config could be parsed and represented with `CheckOptions Maybe`. In the end we resolve the various check options structures into a single `Either SomeError (CheckOptions Identity)`.

Regarding top-level definitions, I'm thinking bare top-level names corresponding to the `CheckOptions` structure:

```purescript
module MySpec where

...

origin = "http://example.com"

tests = 10

maxActions = 50

...
```
