### ISSUE TITLE
Importing Quickstrom dependency for purescript projects

### ISSUE THREAD

**Issue by GrafBlutwurst** [quickstrom/quickstrom#24]
It would be great to have a published library for Quickstrom so it can be imported to have completions etc.

My current hack is to clone Quickstrom and change `package.dhall` of my project so that an addition points to the qucickstrom repo:

`let additions = {=} with quickstrom = ../quickstrom/dsl/spago.dhall as Location`

**Comment by owickstrom** [comment]
Yeah, I've also hacked around this for now. In the Nix shell there's a wrapped `purs ide server` with similar paths configured:

https://github.com/quickstrom/quickstrom/blob/main/shell.nix#L12-L19

Also, I think that the purescript-language-server has support for setting source globs explicitly using an environment variable:

https://github.com/nwolverson/purescript-language-server/pull/76 

For a more nicely packed up solution for Quickstrom, would it make sense to include a language server for specifications in the CLI? You'd need to reconfigure your editor to use `quickstrom` for those files. I really don't want to require people to install the PureScript tools just to write specs (with good editor support).

**Comment by owickstrom** [comment]
Also worth noting, I think publishing a Quickstrom package in the normal PureScript sense would be confusing. It has no value and can't work on its own. It's almost worth thinking about the specification language as _not_ being PureScript, and more like a new language that happens to use PureScript as an implementation detail. The evaluation semantics is and will most likely stay different from PureScript, also.

**Comment by GrafBlutwurst** [comment]
Maybe a good end result could be a section in the doc talking about lsp support for quickstrom docs? One possible solution is spago and a published package of the DSL but maybe there's something better?

**Comment by owickstrom** [comment]
Yeah. I'm going to investigate bundling an LSP thing with quickstrom.

**Comment by owickstrom** [comment]
In the longer run the PureScript-based specs are likely going away, so I've decided to not spend time on this right now. If anyone has suggestions on a low-effort improvement on the current situation, please open a new issue.
