### ISSUE TITLE
Reinstate traces

### ISSUE THREAD

**Issue by owickstrom** [quickstrom/quickstrom#26]
There was support for traces in specs before, but it's silently gone broken.

**Comment by owickstrom** [comment]
I've found no good way of collecting traces in the form Quickstrom used to have, so closing this issue.

**Comment by jleonard-r7** [comment]
What form of traces did Quickstrom used to have? Sounds like it could be useful ...

**Comment by owickstrom** [comment]
Something like `Debug.Trace.trace` in Haskell. But it got very messy with console output, especially since spec expressions might be evaluated multiple times (like in `always`).

Having a way of collecting unique values that some variable has taken would be useful, and displaying those in the test report.
