### ISSUE TITLE
opening a file selection dialog crashes Quickstrom with a 404 error

### ISSUE THREAD

**Issue by BrianHicks** [quickstrom/quickstrom#28]
hey! I've been following your work on this and I'm trying it out on a little tool I wrote to rank random things: https://elo.bytes.zone, source at https://git.bytes.zone/brian/elo-anything.

Problem is, I'm unable to get quickstrom to connect to either a local file (`dist/index.html`) or a local dev server (`http://localhost:8000`.) I'm using the versions specified in the foot of this post, under which invoking quickstrom like this:

```
quickstrom check tests/EloAnything.spec.purs http://localhost:8000/
```

produces this error:

<details>
<summary>Quickstrom Output</summary>

```
   ____       _      _        _
  /___ \_   _(_) ___| | _____| |_ _ __ ___  _ __ ___
 //  / / | | | |/ __| |/ / __| __| '__/ _ \| '_ ` _ \
/ \_/ /| |_| | | (__|   <\__ \ |_| | | (_) | | | | | |
\___,_\ \__,_|_|\___|_|\_\___/\__|_|  \___/|_| |_| |_|

Running 10 tests...

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

10 Actions

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Check encountered an error: user error (E (ResponseError InvalidSessionId "Tried to run command without establishing a connection" "" Nothing (Status {statusCode = 404, statusMessage = "Not Found"})))
```

</details>

which corresponds to this geckodriver output:

<details>
<summary>geckodriver output</summary>

```
1598902629235   mozrunner::runner       INFO    Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-headless" "-private" "-foreground" "-no-remote" "-profile" "/var/folders/1r/_mn2yckn047g2fp6442389580000gn/T/rust_mozprofile5jM5Ev"
*** You are running in headless mode.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
1598902631018   Marionette      INFO    Listening on port 51829
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
Exiting due to channel error.
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
Exiting due to channel error.
Exiting due to channel error.
```

</details>

Finally, here's the contents of `tests/EloAnything.spec.purs`:

<details>
<summary>tests/EloAnything.spec.purs</summary>

```purescript
module EloAnythingSpecification where

import Data.Tuple
import Quickstrom

readyWhen :: Selector
readyWhen = "button"

actions :: Array (Tuple Int Action)
actions = clicks

proposition :: Boolean
proposition = true
```

</details>

I can hit localhost:8000 myself, and can see the commands above requesting the resources, but nothing ever happens.

And last thing: if you want to try and reproduce it yourself, the mentioned repo uses nix/direnv, so hopefully it would not be all that painful! My work so far is on the `quickstrom` branch in that repo.

### Versions

- quickstrom: c103cd337b5d26ba55fda98d5fa456b76c3a4cb4
- geckodriver: 0.26.0

**Comment by owickstrom** [comment]
Thanks for the report! I can't say that I've seen this particular issue before. I'll try checking out your repo and see if I can find out anything.

**Comment by owickstrom** [comment]
Couldn't access the repo you linked. Do I need to authenticate?

BTW, this thread suggests that Firefox (run by Geckodriver) might have crashed:

https://github.com/mozilla/geckodriver/issues/1462

Can you try executing Firefox as Geckodriver does it (I think the exact command is logged), but without `-headless`, and then try accessing your app?

**Comment by BrianHicks** [comment]
oh, oops, I forgot that was private. Now it's public. :)

will try the FF command!

**Comment by BrianHicks** [comment]
so that worked (updated FF to v80 in the process, still crashes)

I wonder if it might be that this app has two file selector buttons on this page, which seemed to be the cause of the crash in the linked issue. I'll try telling Quickstrom to only click non-system-dialog-inducing buttons and report back.

**Comment by owickstrom** [comment]
Ah, yes it might be that file dialog?

Would you mind running Quickstrom with --log-level=DEBUG? Might give some valuable info.

**Comment by BrianHicks** [comment]
mmm, ok, so I marked all my non-file-dialog buttons with `class="safe"` and now I'm getting successful runs (which all pass because of the naive `proposition` but that's fine.)

So it looks like this is an upstream issue instead of a quickstrom issue! That's fine. I'm fine closing this if you don't want to investigate further.

Do you have any advice on how to not change my markup to rely on a class? If I can tell Quickstrom "click any button that does not say 'Save Standings' or 'Load Standings'" it'll be fine. But here's what I have now:

```purescript
actions :: Array (Tuple Int Action)
actions =
    [ Tuple 1 (Focus "input[type=text]")
    , Tuple 1 (Click "button.safe")
    ]
```

---

Wrote the above before you posted your comment. Running `quickstrom check --log-level=DEBUG tests/EloAnything.spec.purs http://localhost:8000` has identical output to above. Running geckodriver with `--log debug` gets me this:

[geckodriver-debug.log](https://github.com/quickstrom/quickstrom/files/5152467/geckodriver-debug.log)

**Comment by owickstrom** [comment]
Thanks, good info! Yeah, https://github.com/mozilla/geckodriver/issues/1173 seems related, too.

I'm not sure about the file downloading case, I'm guessing that could be made to work. Do you know if it's both "Save" and "Load" that crash, or just "Load"?

Regarding the actions, I think it could work with an XPath selector once there's support for it in Quickstrom. I don't think it's hard to implement (basically just forward the string to the underlying WebDriver), but I haven't gotten around to it. Sticking to CSS selectors has some benefits, too, so I should think carefully about it.

Other than that, I think you'll need some class or attribute (on that button or any container) to narrow down the selectors. Perhaps a negation (`:not`) selector so that you don't have to taint everything else?

**Comment by BrianHicks** [comment]
> Do you know if it's both "Save" and "Load" that crash, or just "Load"?

Oh, good question… I'm not sure. But the save/load code is not complicated. It basically just dumps the whole state to JSON and then loads it again, and all the selector/download logic is in the Elm runtime. If I could test it trivially with Quickstrom, I'd go for it, but I'm more than OK with manual testing and automated serialization/deserialization testing for those parts.

If there's no way around using a CSS-style selector, I can live with it… but I'll certainly watch for future releases where I can use xpath or a selection DSL :)

I'm going to go ahead and close this out now, since it seems pretty conclusively to be a bug with something outside this repo.

So to finish up: thanks for making this. I'm looking forward to seeing your bug trophy case grow!

(and thanks for using Nix… I just pulled in the project with `niv` and it installed the correct versions immediately. Love when that happens!)

**Comment by owickstrom** [comment]
OK! I'll probably try to create a small reproduction case with some basic JS, then I perhaps can find a workaround or at least produce a better error message.

Thanks so much for the report and feedback! This is the kind of exposure Quickstrom needs to become more mature, so I'm very happy about it. I hope you get some use out of it already, despite it being a young project.

(and likewise, being able to just clone and run with Nix is a blessing!)

**Comment by owickstrom** [comment]
Been working on a Chromedriver branch. There it actually runs! So there's still hope for elm and file uploads. 😊
