### ISSUE TITLE
Binary LTL Operators

### ISSUE THREAD

**Issue by vladciobanu** [quickstrom/quickstrom#31]
### Until
Example: a form with a few mandatory fields and a button. I'd like to be able to say that the button is disabled until all fields are filled in with some value.

### Release
Example: TODO, find a good example

Bad example: release is the dual of until, so the same example can be reused here; release the requirement that the button must be disabled when all fields are filled in.

(`¬(until p q) = release (¬p) (¬q)`)

**Comment by owickstrom** [comment]
Yeah, I think these can go in. And `release` can be an alias in the PureScript code for the dual `until` which would be a foreign function.

Would you be interested in submitting a PR?

**Comment by vladciobanu** [comment]
Yeah, I think it would be fun to have a go at it. I might try it live on stream on Friday evening!
