### ISSUE TITLE
LTL operator: eventually

### ISSUE THREAD

**Issue by vladciobanu** [quickstrom/quickstrom#32]
Quickstrom is currently missing the `eventually` LTL operator. I understand that the main reasoning is the fact that it's quite a bit harder to verify that something doesn't exist, especially when you run examples.

I'm not sure what the literature says about finite temporal logics (I'll ask around!), but one idea would be to somehow allow explicit annotations regarding to the number of required steps. One could say that some property must hold (restricted always) for at least 50 steps. Or that some property should be true at least once in the next 50 steps (restricted evetually).

**Comment by owickstrom** [comment]
Yeah, the paper I found on this (I'll see if I can dig it up again) basically concluded that liveness properties (like with `eventually`) can need infinite behaviors to be verified.

The idea I've had is to support `eventually` together with coverage checking of some kind. Basically being able to say "there should be at least N tests that reach a specific state". This ties into your #33 proposal, but could be done in others ways too, I guess.

I'm a bit skeptical to the restricted versions with fixed behavior lengths. Not sure, it seems like a weird thing to specify. Do you have any examples or ideas of where it might make sense?

**Comment by vladciobanu** [comment]
I think I'll just jeep a single issue open so we can chat there. I kind of mixed the ideas anyway, but it sort of makes sense: if we find a way to use existentials, that idea might work on both one path (eventually) and probably on multiple paths as well (exists from CTL).
