### ISSUE TITLE
Unpolished idea: CTL operators

### ISSUE THREAD

**Issue by vladciobanu** [quickstrom/quickstrom#33]
Here's a really unpolished idea: what if generating cases would basically generate a tree of cases, like a subset of all possibilities. We could use CTL to reason about various paths within this tree, e.g. assert that there is some property that must hold everywhere, or some property which must hold at least in one branch.

Again, the existential might prove harder to reason about or implement (see #32), but maybe a restricted version would work?

**Comment by vladciobanu** [comment]
I've given this a bit of thought and I have a few questions.

How does the random case generator work? Does it only click on things inside the "readyWhen" element? Does it always click on "clickable" things (which have event handlers)? 

Does it guarantee in any way that it will click my one button on the page? Or will it also do random clicks on other things?

I am asking because I think that we are currently doing some sort of CTL where we always assume the *All* quantifier (https://en.wikipedia.org/wiki/Computation_tree_logic).

We could consider adding the Exists quantifier, but only if there are some sort of guarantees about how test cases are produced. So for example, if we can generate a series of states where we only click one of the two buttons (by random chance), then it's really hard to talk about eventually/exists.

But even so, it is conceivable that we could write some properties like
```purescript
exists some_interesting_path || always the_case_generator_is_being_boring
```
Where `some_interesting_path` is a special case we want to check, and `the case_generator_is_being_boring` means it just wasn't able to find that case.

The question becomes, is this interesting or useful?

**Comment by vladciobanu** [comment]
I think past-time TL might be a better solution, but I need to think about it a bit more.

**Comment by owickstrom** [comment]
I've been working with a researcher on a new temporal logic for Quickstrom, which is largely LTL but with tweaks to enable liveness properties (e.g. `eventually`) together with the testing nature of this project. So I'm going to close this issue as it's a very large undertaking and more like an epic for this project. Thanks for the discussions and interest!
