### ISSUE TITLE
Installing with docker documentation can be closer to typical usecase by addressing localhost (or docker.host.internal for MacOS)

### ISSUE THREAD

**Issue by marvinirwin** [quickstrom/quickstrom#48]
I spent 10 minutes trying to figure out why QuickStrom couldn't see my site running on the [MacOS host system's localhost](https://docs.docker.com/docker-for-mac/networking/)

The Contributing page encourages Nix for development, but if use is encouraged for any platform using docker the instructions could perhaps be closer to the typical usecase.

https://github.com/quickstrom/quickstrom/pull/49

**Comment by owickstrom** [comment]
Closed by #49
