### ISSUE TITLE
Need way to pass chrome arguments

### ISSUE THREAD

**Issue by jleonard-r7** [quickstrom/quickstrom#59]
In particular our development mode of testing requires `--user-data-dir=` for sharing an authenticated user's cookie and `--disable-web-security=` to allow cross-site usage of such cookie.

This line seems to not allow any user-specified arguments:
https://github.com/quickstrom/quickstrom/blob/0145b7be7036d5330f9aa941be58145f11cc4511/runner/src/Quickstrom/WebDriver/WebDriverW3C.hs#L161

**Comment by jleonard-r7** [comment]
Related: #21

**Comment by owickstrom** [comment]
Right, would a command-line parameter for passing additional args work? Would you be interested in submitting a PR? I'm thinking something like adding them to a `Set` first, and then creating the `JSON.Array` from that.

**Comment by jleonard-r7** [comment]
Yea that would work. I'll give a go at creating the PR. Thanks.

**Comment by jleonard-r7** [comment]
This is complete as of #60 being merged.
