### ISSUE TITLE
Actions should be sequence-able

### ISSUE THREAD

**Issue by jleonard-r7** [quickstrom/quickstrom#61]
Related: #21

It would allow for more "targeted" operation if Quickstrom defined the Action data type such as:

```
data BaseAction sel
  = Focus sel
  | KeyPress Char
  | EnterText Text
  | Click sel
  | Navigate Text
  deriving (Eq, Show, Generic, ToJSON)

data Action = Either BaseAction [BaseAction]
```

The implementation of this would fall out naturally as one would expect with the only challenge being deciding if a "sequence of actions" is "possible" or "valid" at any point in time.

**Comment by jleonard-r7** [comment]
Although perhaps determining ahead of time if it is valid would not be required as one could simply attempt to take the full sequence of actions and if at any point, any of the sub-actions were invalid, error back out to the top level and continue on to the next selected action.

**Comment by jleonard-r7** [comment]
(But one may require "reverse-ability" to implement that actually). Reverse-able actions also seem like a useful concept however.

**Comment by jleonard-r7** [comment]
And actually I think the data model looks more like something like this:

```
data BaseAction
  = Focus Selector
  | KeyPress Char
  | EnterText String
  | Click Selector
  | Navigate Path

data Action = Single BaseAction | Sequence (Array BaseAction)

type ProbabilisticAction = (Tuple Int Action)

type Actions
  = Array ProbabilisticAction
```

**Comment by jleonard-r7** [comment]
Also, one shortcut that would work for my current use case (logging the user in) would be to assume that if the first action in an action sequence is "available"/"valid" then the whole sequence must be. I think i will go ahead and implement it like this just to get the ball rolling on it.

**Comment by jleonard-r7** [comment]
FYI... I am working on this at the following branch if you want to review the work in progress / see how it's going:
https://github.com/jleonard-r7/quickstrom/commits/add-action-sequences

**Comment by owickstrom** [comment]
Yeah, this is something I've been meaning to explore, and people have suggested specifically for login scenarios. I'll try to find some time to review your PRs in the coming days. Thanks!

**Comment by jleonard-r7** [comment]
#62 resolves this.
